### ISSUE TITLE
Question about upgrading solc version

### ISSUE THREAD

**Issue by sveitser** [OffchainLabs/nitro-contracts#209]
We have some small additions in our fork https://github.com/EspressoSystems/nitro-contracts for the integration with the Espresso sequencer. We are now running into an issue where `RollupUserLogic.sol` exceeds the 24 kB size limit by a tiny bit (even if we set the optimizer runs to 1).

This problem goes away if we use a newer solc, for example 0.8.26. 

I saw that in https://github.com/OffchainLabs/nitro-contracts/commit/d86ee9dded13fd1718dccd3ef1f62e38dfa8c89f a previous update to solc was reverted. So we're wondering if there any concerns with using more recent versions of solc.

cc @gvladika @imjeremyhe

**Comment by gzeoneth** [comment]
Out of an abundance of caution, we avoid bumping solc version unless necessary. That said, there are no known issue at this moment that bumping solc may causes. 

We are aware of the tight contract size of `RollupUserLogic` and in fact v2.1.0 might have pushed it to the limit. Hopefully this will go away when we ship v3 ([BOLD](https://github.com/OffchainLabs/nitro-contracts/pull/193)) which have a much smaller `RollupUserLogic` size.
