### ISSUE TITLE
contract versioning

### ISSUE THREAD

**Issue by InoMurko** [OffchainLabs/nitro-contracts#248]
Hi team, 

is there an effective way to distinguish Nitro contracts being used by a rollup?
To be completely clear - is there an on-chain way to figure out if a rollup is using `v1.1.0`, `v2.0.0`,`v2.1.0`? Or anything in between?

**Comment by gzeoneth** [comment]
https://github.com/OffchainLabs/orbit-actions?tab=readme-ov-file#check-version-and-upgrade-path
